


   


const applicationdata = [
  {
    name: "kevin",
    country: "aus",
    course: "B.E",
    doj: "11/08/2021",
  },
  {
    name: "tamain",
    country: "india",
    course: "msc",
    doj: "12/08/2023",
  },
  {
    name: "baalaa",
    country: "zimababae",
    course: "bsc",
    doj: "23/09/2023",
  },
  {
    name: "manaikakam",
    country: "U.S.A",
    course: "m.sc",
    doj: "23/5/2023",
  },
  {
    name: "nitasah",
    country: "china",
    course: "m.e",
    doj: "24/09/2023",
  },
  {
    name: "tamain",
    country: "india",
    course: "msc",
    doj: "12/08/2023",
  },
  {
    name: "baalaa",
    country: "zimababae",
    course: "bsc",
    doj: "23/09/2023",
  },
  {
    name: "manaikakam",
    country: "U.S.A",
    course: "m.sc",
    doj: "23/5/2023",
  },
  {
    name: "nitasah",
    country: "china",
    course: "m.e",
    doj: "24/09/2023",
  }
];

const studentinterestdata = [
  {
    course: "B.E",
    Noofstudents: "34",
  },
  {
    course: "M.sc",
    Noofstudents: "22",
  },
  {
    course: "M.E",
    Noofstudents: "20",
  },
  {
    course: "P.hd",
    Noofstudents: "14",
  },
  {
    course: "M.A",
    Noofstudents: "10",
  },
  {
    course: "M.E",
    Noofstudents: "20",
  },
  {
    course: "P.hd",
    Noofstudents: "14",
  },
  {
    course: "M.A",
    Noofstudents: "10",
  }
];

const enquirylist = [
  {
    Name: "Hema",
    Email_id: "hema72@gmail.com",
    Mobile_number: "3545645657",
    Nearest_iiec_office: "chennai",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "kumari",
    Email_id: "kuma@gmail.com",
    Mobile_number: "3434534545",
    Nearest_iiec_office: "chennai",
    Preferred_mode_of_counselling: "offline",
  },
  {
    Name: "Daniel",
    Email_id: "danny@gmail.com",
    Mobile_number: "3243453535",
    Nearest_iiec_office: "australia",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "mansoor",
    Email_id: "mansu@gmail.com",
    Mobile_number: "34354346",
    Nearest_iiec_office: "kerla",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "king salman",
    Email_id: "kinguae@mail.com",
    Mobile_number: "63784738",
    Nearest_iiec_office: "Dubai",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "Hema",
    Email_id: "hema72@gmail.com",
    Mobile_number: "3545645657",
    Nearest_iiec_office: "chennai",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "kumari",
    Email_id: "kuma@gmail.com",
    Mobile_number: "3434534545",
    Nearest_iiec_office: "chennai",
    Preferred_mode_of_counselling: "offline",
  },
  {
    Name: "Daniel",
    Email_id: "danny@gmail.com",
    Mobile_number: "3243453535",
    Nearest_iiec_office: "australia",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "mansoor",
    Email_id: "mansu@gmail.com",
    Mobile_number: "34354346",
    Nearest_iiec_office: "kerla",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "king salman",
    Email_id: "kinguae@mail.com",
    Mobile_number: "63784738",
    Nearest_iiec_office: "Dubai",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "Hema",
    Email_id: "hema72@gmail.com",
    Mobile_number: "3545645657",
    Nearest_iiec_office: "chennai",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "kumari",
    Email_id: "kuma@gmail.com",
    Mobile_number: "3434534545",
    Nearest_iiec_office: "chennai",
    Preferred_mode_of_counselling: "offline",
  },
  {
    Name: "Daniel",
    Email_id: "danny@gmail.com",
    Mobile_number: "3243453535",
    Nearest_iiec_office: "australia",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "mansoor",
    Email_id: "mansu@gmail.com",
    Mobile_number: "34354346",
    Nearest_iiec_office: "kerla",
    Preferred_mode_of_counselling: "online",
  },
  {
    Name: "king salman",
    Email_id: "kinguae@mail.com",
    Mobile_number: "63784738",
    Nearest_iiec_office: "Dubai",
    Preferred_mode_of_counselling: "online",
  },
];

const studentmanagementdata = [
  {
    Employee_Name: "HemaKumar",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "suresh",
    course: "IELTS",
  },
  {
    Employee_Name: "Kumar",
    DOJ: "26-09-2019",
    Employee_id: "35456444357",
    counselling_Country: "U.A.E",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Daniels",
    DOJ: "07-07-2020",
    Employee_id: "3545805668",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Krish",
    DOJ: "14-03-2018",
    Employee_id: "3545645284",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Neeraj",
    DOJ: "26-03-2017",
    Employee_id: "3545645483",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "suresh",
    course: "IELTS",
  },
  {
    Employee_Name: "Bala",
    DOJ: "14-08-2020",
    Employee_id: "3545645386",
    counselling_Country: "Australia",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Sharuk",
    DOJ: "26-02-2020",
    Employee_id: "354564589",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "suresh",
    course: "IELTS",
  },
  {
    Employee_Name: "Salman",
    DOJ: "26-07-2018",
    Employee_id: "354564437854",
    counselling_Country: "Aus",
    Status: "In-Process",
    counsellor: "suresh",
    course: "IELTS",
  },
  {
    Employee_Name: "Harish",
    DOJ: "26-03-2020",
    Employee_id: "3545645574",
    counselling_Country: "U.A.E",
    Status: "In-Process",
    counsellor: "suresh",
    course: "IELTS",
  },
  {
    Employee_Name: "Suresh",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "suresh",
    course: "IELTS",
  },
  {
    Employee_Name: "Dinesh",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Kevin",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "McGregor",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Smith",
    DOJ: "26-07-2018",
    Employee_id: "3545645684",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Warner",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Watson",
    DOJ: "26-07-2018",
    Employee_id: "35456445634",
    counselling_Country: "USA",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Alex",
    DOJ: "26-07-2020",
    Employee_id: "3545645647",
    counselling_Country: "Aus",
    Status: "In-Process",
    counsellor: "ragesh",
    course: "IELTS",
  },
  {
    Employee_Name: "Sathish",
    DOJ: "26-07-2018",
    Employee_id: "3545645244",
    counselling_Country: "Aus",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Dinesh",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Kevin",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "McGregor",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Smith",
    DOJ: "26-07-2018",
    Employee_id: "3545645684",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Warner",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Watson",
    DOJ: "26-07-2018",
    Employee_id: "35456445634",
    counselling_Country: "USA",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Alex",
    DOJ: "26-07-2020",
    Employee_id: "3545645647",
    counselling_Country: "Aus",
    Status: "In-Process",
    counsellor: "Karim",
    course: "IELTS",
  },
  {
    Employee_Name: "Sathish",
    DOJ: "26-07-2018",
    Employee_id: "3545645244",
    counselling_Country: "Aus",
    Status: "In-Process",
    counsellor: "Karim",
    course: "IELTS",
  },
  {
    Employee_Name: "Sathish",
    DOJ: "26-07-2018",
    Employee_id: "3545645244",
    counselling_Country: "Aus",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Dinesh",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Kevin",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "McGregor",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Smith",
    DOJ: "26-07-2018",
    Employee_id: "3545645684",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Warner",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Watson",
    DOJ: "26-07-2018",
    Employee_id: "35456445634",
    counselling_Country: "USA",
    Status: "In-Process",
    counsellor: "alex",
    course: "IELTS",
  },
  {
    Employee_Name: "Alex",
    DOJ: "26-07-2020",
    Employee_id: "3545645647",
    counselling_Country: "Aus",
    Status: "In-Process",
    counsellor: "Karim",
    course: "IELTS",
  },
  {
    Employee_Name: "Sathish",
    DOJ: "26-07-2018",
    Employee_id: "3545645244",
    counselling_Country: "Aus",
    Status: "In-Process",
    counsellor: "Karim",
    course: "IELTS",
  },
];


const employeemanagementdata = [
  {
    Employee_Name: "HemaKumar",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
  {
    Employee_Name: "Kumar",
    DOJ: "26-09-2019",
    Employee_id: "35456444357",
    counselling_Country: "U.A.E",
    Address: "Washington , USA",
    Attendance: "Present",
    No_of_students: 4,
  },
  {
    Employee_Name: "Daniels",
    DOJ: "07-07-2020",
    Employee_id: "3545805668",
    counselling_Country: "India",
    Address: "Mumbai , India",
    Attendance: "Present",
    No_of_students: 1,
  },
  {
    Employee_Name: "Krish",
    DOJ: "14-03-2018",
    Employee_id: "3545645284",
    counselling_Country: "India",
    Address: "Chennai , India",
    Attendance: "Present",
    No_of_students: 5,
  },
  {
    Employee_Name: "Neeraj",
    DOJ: "26-03-2017",
    Employee_id: "3545645483",
    counselling_Country: "India",
    Address: "Madurai , India",
    Attendance: "Present",
    No_of_students: 3,
  },
  {
    Employee_Name: "Bala",
    DOJ: "14-08-2020",
    Employee_id: "3545645386",
    counselling_Country: "Australia",
    Address: " Melbourne , Aus",
    Attendance: "Present",
    No_of_students: 3,
  },
  {
    Employee_Name: "Sharuk",
    DOJ: "26-02-2020",
    Employee_id: "354564589",
    counselling_Country: "India",
    Address: "DElhi , India",
    Attendance: "Present",
    No_of_students: 5,
  },
  {
    Employee_Name: "Salman",
    DOJ: "26-07-2018",
    Employee_id: "354564437854",
    counselling_Country: "Aus",
    Address: "Texas , Aus",
    Attendance: "Present",
    No_of_students: 4,
  },
  {
    Employee_Name: "Harish",
    DOJ: "26-03-2020",
    Employee_id: "3545645574",
    counselling_Country: "U.A.E",
    Address: "Dubai , UAE",
    Attendance: "Present",
    No_of_students: 7,
  },
  {
    Employee_Name: "Suresh",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
  {
    Employee_Name: "Dinesh",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
  {
    Employee_Name: "Kevin",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 4,
  },
  {
    Employee_Name: "McGregor",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
  {
    Employee_Name: "Smith",
    DOJ: "26-07-2018",
    Employee_id: "3545645684",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
  {
    Employee_Name: "Warner",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 4,
  },
  {
    Employee_Name: "Watson",
    DOJ: "26-07-2018",
    Employee_id: "35456445634",
    counselling_Country: "USA",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 4,
  },
  {
    Employee_Name: "Alex",
    DOJ: "26-07-2020",
    Employee_id: "3545645647",
    counselling_Country: "Aus",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 6,
  },
  {
    Employee_Name: "Sathish",
    DOJ: "26-07-2018",
    Employee_id: "3545645244",
    counselling_Country: "Aus",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
  {
    Employee_Name: "Dinesh",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 3,
  },
  {
    Employee_Name: "Kevin",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 4,
  },
  {
    Employee_Name: "McGregor",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
  {
    Employee_Name: "Smith",
    DOJ: "26-07-2018",
    Employee_id: "3545645684",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 5,
  },
  {
    Employee_Name: "Warner",
    DOJ: "26-07-2018",
    Employee_id: "3545645657",
    counselling_Country: "India",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
  {
    Employee_Name: "Watson",
    DOJ: "26-07-2018",
    Employee_id: "35456445634",
    counselling_Country: "USA",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 4,
  },
  {
    Employee_Name: "Alex",
    DOJ: "26-07-2020",
    Employee_id: "3545645647",
    counselling_Country: "Aus",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 5,
  },
  {
    Employee_Name: "Sathish",
    DOJ: "26-07-2018",
    Employee_id: "3545645244",
    counselling_Country: "Aus",
    Address: "Texas , USA",
    Attendance: "Present",
    No_of_students: 2,
  },
];

export {
  applicationdata,
  studentinterestdata,
  enquirylist,
  employeemanagementdata,
  studentmanagementdata,
};
